### PR TITLE
Fix invalid method call to enable service account usage

### PR DESCRIPTION
**Pull request by nickmoorman**
Simple fix for the issue described in #23.

### CODE REVIEW

**Comment by nickmoorman** [comment]
I signed it!

**Comment by silviulica** [comment]
@nickmoorman - Thanks for the contribution! We moved development to Apache Beam repo: https://github.com/apache/incubator-beam/tree/python-sdk/sdks/python

Sorry we will put an update here that this has moved. If you have time please contribute the fix over there since that it is the code base that we use for releases moving forward. If you do not have time let me know and we can port the fix. The contributors guide for Apache Beam is here: http://beam.incubator.apache.org/contribution-guide/

Thanks and apologies again!
Silviu

**Comment by nickmoorman** [comment]
Thanks for the info, Silviu.  I'll port my fix to that repo later today.

**Comment by aaltay** [comment]
Hi @nickmoorman, this is already fixed in the new repository here (https://github.com/apache/beam/blob/master/sdks/python/apache_beam/internal/gcp/auth.py#L156). I am closing this. Thank you for your contribution.

**Pull request closed without merging**
